services:
  api:
    container_name: kattbo-vvo-api.${ENVIRONMENT}
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - kattbo_vvo_logs:/app/logs
      - ~/kattbo-vvo/secrets/ca.cer:/app/secrets/ca.cer:ro,z
      - ~/kattbo-vvo/secrets/kattbo_vvo_api.crt:/app/secrets/certfile.crt:ro,z
      - ~/kattbo-vvo/secrets/kattbo_vvo_api.key:/app/secrets/keyfile.key:ro,z
    ports:
      - 8000:8000
    env_file:
      - ~/kattbo-vvo/secrets/.env-api
    healthcheck:
      test: curl --fail https://localhost:8000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  frontend: 
    container_name: kattbo-vvo-frontend.${ENVIRONMENT}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8001:443
    volumes: 
      - ~/kattbo-vvo/secrets/kattbo_vvo_api.crt:/etc/nginx/ssl/certfile.crt:ro,z
      - ~/kattbo-vvo/secrets/kattbo_vvo_api.key:/etc/nginx/ssl/keyfile.key:ro,z
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ~/kattbo-vvo/images:/usr/share/nginx/html/images:ro,z
    environment:
      - ENVIRONMENT=development
    
  filebeat:
    container_name: kattbo-vvo-filebeat.${ENVIRONMENT}
    image: docker.elastic.co/beats/filebeat:8.13.4
    entrypoint: "filebeat -e -strict.perms=false"
    restart: always
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,z
      - ~/kattbo-vvo/secrets/ca.cer:/usr/share/filebeat/ca.cer:ro,z
      - kattbo_vvo_logs:/var/log/api/:ro
    env_file:
      - ~/kattbo-vvo/secrets/.env-filebeat

volumes:
  kattbo_vvo_logs:
  kattbo_vvo_images: