version: '3.8'

services:
  api:
    container_name: kattbo-vvo-api.${ENVIRONMENT}
    build:
      context: ./api
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    volumes:
      - kattbo_vvo_api_logs:/app/logs
    env_file:
      - .env
    restart: always

  filebeat:
    container_name: kattbo-vvo-filebeat.${ENVIRONMENT}
    image: docker.elastic.co/beats/filebeat:8.15.4
    volumes: 
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - kattbo_vvo_api_logs:/var/log/api:ro
    restart: always

    depends_on:
      - api

volumes:
  kattbo_vvo_api_logs: