services:
  api:
    container_name: kattbo-vvo-api.${ENVIRONMENT}
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    volumes:
      - kattbo_vvo_api_logs:/app/logs
    env_file:
      - .env

  filebeat:
    container_name: kattbo-vvo-filebeat
    image: docker.elastic.co/beats/filebeat:8.15.4
    restart: always
    volumes: 
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./ca.cer:/usr/share/filebeat/ca.cer:ro
      - kattbo_vvo_api_logs:/var/log/api/:ro
    depends_on:
      - api
    env_file:
      - .env

volumes:
  kattbo_vvo_api_logs: