version: '3.8'

services:
  api:
    container_name: kattbo-vvo-api.${ENVIRONMENT}
    user: "appuser"
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api
    ports: 8000:8000
    volumes:
      - apilogs:/app/logs
    env_file:
      - .env
    restart: always

  filebeat:
    container_name: kattbo-vvo-filebeat.${ENVIRONMENT}
    image: docker.elastic.co/beats/filebeat:latest
  volumes: 
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    - api_logs:/var/log/api:ro
  restart: always

volumes:
  api_logs: