version: '3.8'

services:
  web:
    container_name: web-${FLASK_ENV}
    user: "1000:1000"
    build:
      context: .
      dockerfile: ./web/Dockerfile
      target: web
    ports: 
      - "${GUNICORN_PORT}:5000"
    volumes:
    - /srv/kattbo-vvo/uploads:/usr/src/kattbo-vvo/uploads
    - /srv/kattbo-vvo/logs:/usr/src/kattbo-vvo/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web_celery_worker:
    container_name: web_celery_worker-${FLASK_ENV}
    user: "1000:1000"
    build:
      context: .
      dockerfile: ./web/Dockerfile
      target: web_celery_worker
    env_file:
      - .env
    depends_on:
      - web
    healthcheck:
      test: ["CMD-SHELL", "celery -A make_celery.celery inspect ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

