name: API CD/CI - Development

on: 
  push:
    branches:
      - development
    paths:
      - .github/workflows/dev-deploy_api.yml
      - 'docker-compose.yml'
      - 'api/**'
  pull_request:
    paths:
      - .github/workflows/dev-deploy_api.yml
      - 'docker-compose.yml'
      - 'api/**'

env:
  ENVIRONMENT: development
  SERVICE_NAME: Kattbo_VVO-API
  SQL_DATABASE_URL: ${{ secrets.SQL_DATABASE_URL }}
  SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
  AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
  API_AUDIENCE: ${{ secrets.API_AUDIENCE }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
  APM_SERVER_URL: ${{ secrets.APM_SERVER_URL }}
  APM_SECRET_TOKEN: ${{ secrets.APM_SECRET_TOKEN }}
  APM_API_KEY: ${{ secrets.APM_API_KEY }}
  SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
  SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/development'

    steps:
      - uses: actions/checkout@v2

      - name: Building API containers
        run: |
          docker-compose -f docker-compose.yml build api

      - name: Deploying API
        run: |
          docker-compose down api --remove-orphans
          docker-compose up api -d

