on:
  workflow_call:
    secrets:
      SQL_DATABASE_URL:
        required: true
      SESSION_SECRET_KEY:
        required: true
      AUTH0_DOMAIN:
        required: true
      API_AUDIENCE:
        required: true
      JWT_SECRET:
        required: true
      JWT_ALGORITHM:
        required: true
      APM_SERVER_URL:
        required: true
      APM_SECRET_TOKEN:
        required: true
      APM_API_KEY:
        required: true
      SMTP_SERVER:
        required: true
      SMTP_USERNAME:
        required: true
      SMTP_PASSWORD:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: true
      ES_HOSTS:
        required: true
      FILEBEAT_API_KEY:
        required: true
      CERTIFICATE_AUTHORITY:
        required: true
        
jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: creating the .env file
        run: |
          echo "SERVICE_NAME=Kattbo_VVO-API" >> .env
          echo "ENVIRONMENT=development" >> .env
          echo "SQL_DATABASE_URL=${{ secrets.SQL_DATABASE_URL }}" >> .env
          echo "SESSION_SECRET_KEY=${{ secrets.SESSION_SECRET_KEY }}" >> .env
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
          echo "API_AUDIENCE=${{ secrets.API_AUDIENCE }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }}" >> .env
          echo "APM_SERVER_URL=${{ secrets.APM_SERVER_URL }}" >> .env
          echo "APM_SECRET_TOKEN=${{ secrets.APM_SECRET_TOKEN }}" >> .env
          echo "APM_API_KEY=${{ secrets.APM_API_KEY }}" >> .env
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "ES_HOSTS=${{ secrets.ES_HOSTS }}" >> .env
          echo "FILEBEAT_API_KEY=${{ secrets.FILEBEAT_API_KEY }}" >> .env
          echo "${{ secrets.CERTIFICATE_AUTHORITY }}" >> ca.cer

      - name: Upload .env as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env

  ca:
    runs-on: ubuntu-latest
    steps:
      - name: Creating certificate authority file
        run: |
          echo "${{ secrets.CERTIFICATE_AUTHORITY }}" >> ca.cer

      - name: Upload .env as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env

      - name: Upload ca.cer as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ca-file
          path: ca.cer