name: Filebeat CD/CI - Development

on: 
  push:
    branches:
      - development
    paths:
      - .github/workflows/dev-deploy_filebeat.yml
      - 'docker-compose.yml'
      - 'filebeat.yml'
  pull_request:
    paths:
      - .github/workflows/dev-deploy_filebeat.yml
      - 'docker-compose.yml'
      - 'filebeat.yml'

env:
  ENVIRONMENT: development
  ES_HOSTS: ${{ secrets.ES_HOSTS }}
  FILEBEAT_API_KEY: ${{ secrets.FILEBEAT_API_KEY }}

jobs:
  setup:
    uses: eijnar/kattbo-vvo-web/.github/workflows/dev-setup.yml@development
    secrets: inherit
  
  build-and-deploy:
    needs: setup
    runs-on: self-hosted
    if: github.ref == 'refs/heads/development'

    steps:
      - uses: actions/checkout@v4

      - name: Download .env
        uses: actions/download-artifact@v3
        with:
          name: env-files
          path: .

      - name: Download certificate authority
        uses: actions/download-artifact@v3
        with:
          name: ca-file
          path: .

      - name: Pulling filebeat image from Docker.io
        run: |
          docker-compose -f docker-compose.yml pull filebeat

      - name: Deploying Filebeat
        run: |
          docker-compose down filebeat --remove-orphans
          docker-compose up filebeat -d

