# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Kättbo VVOs hemsida

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        echo "$MAIL_USERNAME"
        python -m pip install --upgrade pip
        pip install wheel
        pip install gunicorn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start Flask server
      run: gunicorn 'app:create_app()'

