# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Kättbo VVOs hemsida

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  MAIL_USERNAME: 
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD}}
  MAIL_SERVER: ${{ secrets.MAIL_SERVER}}
  SECRET_KEY: ${{ secrets.SECRET_KEY}}
  SECURITY_PASSWORD_SALT: ${{ secrets.SECURITY_PASSWORD_SALT}}
  SECURITY_PASSWORD_HASH: ${{ secrets.SECURITY_PASSWORD_HASH}}
  SECURITY_TRACKABLE: ${{ secrets.SECURITY_TRACKABLE}}
  SECURITY_REGISTERABLE: ${{ secrets.SECURITY_REGISTERABLE}}
  SECURITY_CONFIRMABLE: ${{ secrets.SECURITY_CONFIRMABLE}}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY}}
  JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM}}
  SQLALCHEMY_DATABASE_URI_DEV: ${{ secrets.SQLALCHEMY_DATABASE_URI_DEV}}
  
permissions:
  contents: write

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.9-1"
    - name: Install dependencies
      run: |
        echo "$MAIL_USERNAME"
        python -m pip install --upgrade pip
        pip install wheel
        pip install gunicorn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start Flask server
      run: gunicorn 'app:create_app()'

