name: Frontend & celery worker CD/CI

on: 
  push:
    branches:
      - main
      - development
    paths:
      - 'web/**'
      - 'common/**'
      - 'docker-compose.yml'
  pull_request:
    paths:
      - 'web/**'
      - 'common/**'
      - 'docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: 
      name: ${{ github.ref == 'refs/heads/main' ? 'production' : 'development' }}

    steps:
      - uses: actions/checkout@v2


      - name: Creating the .env file
        run: |
          echo "FLASK_ENV='${{ env.FLASK_ENV }}'" >> .env
          echo "GUNICORN_PORT=${{ env.GUNICORN_PORT}}" >> .env
          echo "API_BASE='${{ env.API_BASE }}'" >> .env
          echo "UPLOAD_FOLDER='/usr/src/kattbo-vvo/uploads'" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_PORT=465" >> .env
          echo "MAIL_USE_SSL=True" >> .env
          echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
          echo "MAIL_DEFAULT_SENDER_DEV='development@kattbovvo.se'" >> .env
          echo "MAIL_DEFAULT_SENDER_PROD='info@kattbovvo.se'" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "SECURITY_PASSWORD_SALT=${{ secrets.SECURITY_PASSWORD_SALT }}" >> .env
          echo "SECURITY_PASSWORD_HASH=${{ secrets.SECURITY_PASSWORD_HASH }}" >> .env
          echo "SECURITY_REGISTERABLE=True" >> .env
          echo "SECURITY_CONFIRMABLE=True" >> .env
          echo "SECURITY_TRACKABLE=True" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }}" >> .env
          echo "SQLALCHEMY_DATABASE_URI_DEV=${{ secrets.SQLALCHEMY_DATABASE_URI_DEV }}" >> .env
          echo "CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}" >> .env
          echo "CELERY_BACKEND_URL=${{ secrets.CELERY_BACKEND_URL }}" >> .env
          echo "ELASTIC_SECRET_TOKEN=${{ secrets.ELASTIC_SECRET_TOKEN }}" >> .env
          echo "ELASTIC_SERVER_URL=${{ secrets.ELASTIC_SERVER_URL }}" >> .env
          echo "LOG_FILE_PATH='/usr/srv/kattbo-vvo/logs" >> .env

      - name: Building the containers
        run: |
          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml build

      - name: Deploying the frontend and celery worker
        run: |
          docker-compose down --remove-orphans
          docker-compose up -d

