name: Frontend & celery worker CD/CI

on: 
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'common/**'
      - 'Dockerfile.web'
      - 'docker-compose.yml'
  pull_request:
    paths:
      - 'web/**'
      - 'common/**'
      - 'Dockerfile.web'
      - 'docker-compose.yml'
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      UPLOAD_FOLDER: '/srv/kattbo-vvo/upload'
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_PORT: 465
      MAIL_USE_SSL: True
      MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
      MAIL_DEFAULT_SENDER_DEV: 'development@kattbovvo.se'
      MAIL_DEFAULT_SENDER_PROD: 'info@kattbovvo.se'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SECURITY_PASSWORD_SALT: ${{ secrets.SECURITY_PASSWORD_SALT }}
      SECURITY_PASSWORD_HASH: ${{ secrets.SECURITY_PASSWORD_HASH }}
      SECURITY_REGISTERABLE: True
      SECURITY_CONFIRMABLE: True
      SECURITY_TRACKABLE: True
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
      SQLALCHEMY_DATABASE_URI_DEV: ${{ secrets.SQLALCHEMY_DATABASE_URI_DEV }}
      CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
      CELERY_BACKEND_URL: ${{ secrets.CELERY_BACKEND_URL }}
      ELASTIC_SECRET_TOKEN: ${{ secrets.ELASTIC_SECRET_TOKEN }}
      ELASTIC_SERVER_URL: ${{ secrets.ELASTIC_SERVER_URL }}

    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Build the container
        run: |
          docker-compose -f docker-compose.yml build web

      - name: Deploy deploy the frontend and celery worker
        run: |
          docker-compose up -d web
          docker-compose up -d web_celery_worker

